<?php

namespace Kurusa\Fortnox\Responses\Orders;

final readonly class Order
{
    /**
     * @param OrderRow[] $orderRows
     * @param string[]   $labels
     */
    public function __construct(
        public string $documentNumber,
        public ?string $customerNumber,
        public ?string $customerName,
        public ?string $orderDate,
        public ?string $orderType,
        public ?string $deliveryDate,
        public ?float $administrationFee,
        public ?float $administrationFeeVat,
        public ?string $address1,
        public ?string $address2,
        public ?float $basisTaxReduction,
        public ?string $city,
        public ?string $country,
        public ?string $comments,
        public ?float $contributionPercent,
        public ?float $contributionValue,
        public ?string $copyRemarks,
        public ?string $costCenter,
        public ?string $currency,
        public ?float $currencyRate,
        public ?float $currencyUnit,
        public ?string $deliveryState,
        public ?string $deliveryAddress1,
        public ?string $deliveryAddress2,
        public ?string $deliveryCity,
        public ?string $deliveryCountry,
        public ?string $deliveryName,
        public ?string $deliveryZipCode,
        public ?string $externalInvoiceReference1,
        public ?string $externalInvoiceReference2,
        public ?string $emailAddressFrom,
        public ?string $emailAddressTo,
        public ?float $freight,
        public ?float $freightVat,
        public ?float $gross,
        public ?bool $houseWork,
        public ?string $invoiceReference,
        public array $labels,
        public ?string $language,
        public ?float $net,
        public ?bool $notCompleted,
        public ?string $offerReference,
        public ?string $organisationNumber,
        public ?string $outboundDate,
        public ?string $phone1,
        public ?string $phone2,
        public ?string $priceList,
        public ?string $printTemplate,
        public ?string $project,
        public ?string $remarks,
        public ?float $roundOff,
        public bool $sent,
        public ?float $taxReduction,
        public ?string $termsOfDelivery,
        public ?string $termsOfPayment,
        public ?float $total,
        public ?float $totalToPay,
        public ?float $totalVat,
        public ?bool $vatIncluded,
        public ?bool $warehouseReady,
        public ?string $wayOfDelivery,
        public ?string $yourOrderNumber,
        public ?string $yourReference,
        public ?string $zipCode,
        public ?string $stockPointCode,
        public ?string $stockPointId,
        public bool $cancelled,
        public array $orderRows,
    )
    {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            documentNumber: (string)($data['DocumentNumber'] ?? ''),
            customerNumber: $data['CustomerNumber'] ?? null,
            customerName: $data['CustomerName'] ?? null,
            orderDate: $data['OrderDate'] ?? null,
            orderType: $data['OrderType'] ?? null,
            deliveryDate: $data['DeliveryDate'] ?? null,
            administrationFee: isset($data['AdministrationFee']) ? (float)$data['AdministrationFee'] : null,
            administrationFeeVat: isset($data['AdministrationFeeVAT']) ? (float)$data['AdministrationFeeVAT'] : null,
            address1: $data['Address1'] ?? null,
            address2: $data['Address2'] ?? null,
            basisTaxReduction: isset($data['BasisTaxReduction']) ? (float)$data['BasisTaxReduction'] : null,
            city: $data['City'] ?? null,
            country: $data['Country'] ?? null,
            comments: $data['Comments'] ?? null,
            contributionPercent: isset($data['ContributionPercent']) ? (float)$data['ContributionPercent'] : null,
            contributionValue: isset($data['ContributionValue']) ? (float)$data['ContributionValue'] : null,
            copyRemarks: $data['CopyRemarks'] ?? null,
            costCenter: $data['CostCenter'] ?? null,
            currency: $data['Currency'] ?? null,
            currencyRate: isset($data['CurrencyRate']) ? (float)$data['CurrencyRate'] : null,
            currencyUnit: isset($data['CurrencyUnit']) ? (float)$data['CurrencyUnit'] : null,
            deliveryState: $data['DeliveryState'] ?? null,
            deliveryAddress1: $data['DeliveryAddress1'] ?? null,
            deliveryAddress2: $data['DeliveryAddress2'] ?? null,
            deliveryCity: $data['DeliveryCity'] ?? null,
            deliveryCountry: $data['DeliveryCountry'] ?? null,
            deliveryName: $data['DeliveryName'] ?? null,
            deliveryZipCode: $data['DeliveryZipCode'] ?? null,
            externalInvoiceReference1: $data['ExternalInvoiceReference1'] ?? null,
            externalInvoiceReference2: $data['ExternalInvoiceReference2'] ?? null,
            emailAddressFrom: $data['EmailInformation']['EmailAddressFrom'] ?? null,
            emailAddressTo: $data['EmailInformation']['EmailAddressTo'] ?? null,
            freight: isset($data['Freight']) ? (float)$data['Freight'] : null,
            freightVat: isset($data['FreightVAT']) ? (float)$data['FreightVAT'] : null,
            gross: isset($data['Gross']) ? (float)$data['Gross'] : null,
            houseWork: isset($data['HouseWork']) ? (bool)$data['HouseWork'] : null,
            invoiceReference: $data['InvoiceReference'] ?? null,
            labels: $data['Labels'] ?? [],
            language: $data['Language'] ?? null,
            net: isset($data['Net']) ? (float)$data['Net'] : null,
            notCompleted: isset($data['NotCompleted']) ? (bool)$data['NotCompleted'] : null,
            offerReference: $data['OfferReference'] ?? null,
            organisationNumber: $data['OrganisationNumber'] ?? null,
            outboundDate: $data['OutboundDate'] ?? null,
            phone1: $data['Phone1'] ?? null,
            phone2: $data['Phone2'] ?? null,
            priceList: $data['PriceList'] ?? null,
            printTemplate: $data['PrintTemplate'] ?? null,
            project: $data['Project'] ?? null,
            remarks: $data['Remarks'] ?? null,
            roundOff: isset($data['RoundOff']) ? (float)$data['RoundOff'] : null,
            sent: !empty($data['Sent']),
            taxReduction: isset($data['TaxReduction']) ? (float)$data['TaxReduction'] : null,
            termsOfDelivery: $data['TermsOfDelivery'] ?? null,
            termsOfPayment: $data['TermsOfPayment'] ?? null,
            total: isset($data['Total']) ? (float)$data['Total'] : null,
            totalToPay: isset($data['TotalToPay']) ? (float)$data['TotalToPay'] : null,
            totalVat: isset($data['TotalVAT']) ? (float)$data['TotalVAT'] : null,
            vatIncluded: isset($data['VATIncluded']) ? (bool)$data['VATIncluded'] : null,
            warehouseReady: isset($data['WarehouseReady']) ? (bool)$data['WarehouseReady'] : null,
            wayOfDelivery: $data['WayOfDelivery'] ?? null,
            yourOrderNumber: $data['YourOrderNumber'] ?? null,
            yourReference: $data['YourReference'] ?? null,
            zipCode: $data['ZipCode'] ?? null,
            stockPointCode: $data['StockPointCode'] ?? null,
            stockPointId: $data['StockPointId'] ?? null,
            cancelled: !empty($data['Cancelled']),
            orderRows: array_map(
                static fn(array $row): OrderRow => OrderRow::fromArray($row),
                $data['OrderRows'] ?? [],
            ),
        );
    }
}
